### ISSUE TITLE
Altitude panel not working properly in grafana

### ISSUE THREAD

**Issue by Elm000** [mzac/gpsd-influx#1]
Hey,

The setup is running nice and looking good, but for some reason the altitude heatmap panel isn't working. It gives me the error "Cannot read property 'value' of undefined". It uses the same metrics as the altitude graph below it and that one works just fine. I'm not very experienced with influx and grafana, so if you could show me in the right direction it would be a lot of help.

![grafana](https://user-images.githubusercontent.com/8805630/81557713-1af69800-9395-11ea-99ff-3a39fad46d07.png)

**Comment by mzac** [comment]
Can you try running the bash script with the --debug flag to see if the script is seeing the altitude before sending it to Influx?

https://github.com/mzac/gpsd-influx/blob/master/gpsd-influx.sh#L60

**Comment by Elm000** [comment]
Like this?


TPV
{
    "alt": 216.642,
    "class": "TPV",
    "climb": -0.02,
    "device": "/dev/ttyUSB0",
    "epc": 71.49,
    "eps": 24.25,
    "ept": 0.005,
    "epv": 35.744,
    "epx": 12.016,
    "epy": 12.123,
    "lat": xxxxxxxxxxx
    "lon": xxxxxxxxxx
    "mode": 3,
    "speed": 0.306,
    "time": "2020-05-11T12:04:56.000Z",
    "track": 359.1006
}

Sending to Influx:
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=alt value=216.642
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=climb value=-0.02
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=epc value=71.49
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=eps value=24.25
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=ept value=0.005
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=epv value=35.744
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=epx value=12.016
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=epy value=12.123
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=lat value=xxxxxxxxxxxx
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=lon value=xxxxxxxxxxx
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=mode value=3
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=speed value=0.306
gpsd,host=raspberrypi,device="/dev/ttyUSB0",tpv=track value=359.1006

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: a2bd4393-937f-11ea-82ed-b827ebe2be80
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.0
X-Request-Id: a2bd4393-937f-11ea-82ed-b827ebe2be80
Date: Mon, 11 May 2020 12:04:58 GMT

**Comment by mzac** [comment]
Ok so yes it is receiving the correct data.  There should also be a single stat block that shows the average altitude, is it showing it?  There are also queries you could run against the influxdb directly to get the data points to see if they are there.  I'd have to look them up.

BTW if you'd like, maybe edit your post and remove your exact lat/lon :)

**Comment by Elm000** [comment]
Yes, it shows the current and average altitude blocks. Basically everything else in the dashboard works except for the heatmap. 

Yeah, removing the lat/lon is probably a good idea haha. 

![altitude](https://user-images.githubusercontent.com/8805630/81566535-b0008d80-93a3-11ea-8c66-33eb76c26e86.png)

**Comment by mzac** [comment]
Hmm.. maybe try clone the altitude panel and then change it to heatmap?  I've seen issues with Grafana before when new versions come out the way panels work.  Once you clone it, go into edit and then into the second icon (visualization) and choose the visualization at the top.
![image](https://user-images.githubusercontent.com/10270879/81566981-a5c19d80-9369-11ea-823e-7cb5ca9bf5dd.png)

BTW your lat/lon is still in the debug output!

**Comment by Elm000** [comment]
After looking arond in the settings i found the problem. The heatmaps color scheme wasn't set to anything. It's working fine now, thanks. :)

Oh yeah didn't notice it was there twice, now the lat/lon should be gone...I hope.

**Comment by mzac** [comment]
Ok! Great to see you got it working, I think you're the first person that has given me feedback on this.  BTW if you're interested I did write the script in Python as well.  I haven't done much testing with it but you're free to give it a try.  I'll upload the code to the repo.

**Comment by mzac** [comment]
https://github.com/mzac/gpsd-influx/blob/master/gpsd-influx.py

**Comment by Elm000** [comment]
Hey!

I've been trying out the python version but I cant seem to get it to send the data to Influxdb. Using the debug flag shows i'm getting data from the GPS. Difference this time is that I'm sending the data to a remote server, previously it was a in a local network. 

I was going to try to use the non python script but it doesn't have the option to specify port and credentials like the python one has. I don't think it's going to be much use unless I can add them, not sure how to though. 

I already have another python script running and successfully sending data to the db so it shouldn't be the issue.
