### ISSUE TITLE
Cant send data to database on the python version.

### ISSUE THREAD

**Issue by Elm000** [mzac/gpsd-influx#2]
Hey!

I've been trying out the python version but I cant seem to get it to send the data to Influxdb. Using the debug flag shows i'm getting data from the GPS. Difference this time is that I'm sending the data to a remote server, previously it was a in a local network.

I was going to try to use the non python script but it doesn't have the option to specify port and credentials like the python one has. I don't think it's going to be much use unless I can add them, not sure how to though.

I already have another python script running and successfully sending data to the db so it shouldn't be the issue.

**Comment by mzac** [comment]
Did you figure it out?

**Comment by Elm000** [comment]
Yes, it was actually working but since it used different names for values and stuff my queries ended up being wrong and not returning anything.

**Comment by mzac** [comment]
Ok glad you figured it out!
