### ISSUE TITLE
unary operator expected

### ISSUE THREAD

**Issue by pkkrusty** [mzac/gpsd-influx#4]
I'm on Rasbian Buster and getting the following error show up in syslog:

 `/opt/gpsd-influx/gpsd-influx.sh: line 60: [: -eq: unary operator expected`
Also on line 72.

I took a look at the code and changed `if [ $debug_output -eq 1 ]; then` to `if [ "$debug_output" = 1 ]; then` but I'm not good enough in bash scripts to know if that will work correctly.  The error is gone, in any case.

And getting  `gpspipe: fflush error, Broken pipe(32)` which I think is unrelated. Any ideas?

**Comment by mzac** [comment]
I haven't had a chance to check it out, but have you tried using the python script instead of the bash script?

https://github.com/mzac/gpsd-influx/blob/master/gpsd-influx.py

**Comment by sabey** [comment]
setting `debug_output=0` at the top gets rid of the unary issue but I can't seem to find a fix for `gpspipe: fflush error, Broken pipe(32)`
